config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  resources :gossips do
  		resources :comments
  end
  resources :user
  resources :team, only:[:index]
  resources :contacts, only:[:index]
  resources :city, only:[:show]
  resources :session, only:[:new, :create, :destroy]
  resources :like, only:[:create, :destroy]
  # get 'welcome/', to: 'gossip#home'
  # get 'welcome/:user_name', to: 'gossip#homesecret', as: 'welcome_secret'
  # get 'gossip/:id', to:'gossip#index', as: 'gossip'
  # get 'create_gossip', to: 'gossip#create_gossip'
  # get 'contacts', to: 'gossip#contacts'
  # get 'team', to: 'gossip#team'
  # get 'user/:id', to:'gossip#user', as: 'user'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.or/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	#validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	belongs_to :commentable, polymorphic: true, optional: true
	has_many :likes
	has_many :comments, as: :commentable
	validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :join_gossip_tags
	has_many :tags, through: :join_gossip_tags
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	validates :title, 
		presence: true,
		length: {in: 3..50, message: "length must be between 3 and 50 characters long"}
	validates :content,
		presence: {message: "must exist"} 
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip, optional: true
	belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	has_many :recipient_lists
	validates :content, presence: {message: "must exist"} 
end

app/models/recipient_list.rb
class RecipientList < ApplicationRecord
	belongs_to :private_message
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_gossip_tags
	has_many :gossips, through: :join_gossip_tags
	validates :title, presence: {message: "Please indicate a title for your tag"} 
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
	has_many :comments
	validates :first_name, presence: {message: "must exist"} 
	validates :last_name, presence: {message: "must exist"} 
	validates :age, presence: {message: "must exist"} 
	validates :email, 
		presence: {message: "must be indicated"},
		uniqueness: {message: "already exists"},
		format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Enter a valid email format xxx@yyy.zzz" }
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def index
  end

  def show
    @city = City.find(params[:id].to_i)
    @all_users = @city.users
    puts "$"*10
    puts @city
    puts @all_users
    puts "$"*10
  end

  def new
  end
  
  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user, only: [:new, :edit, :update, :destroy, :create]

  def index
  end

  def show
  end

  def new
  end
  
  def create
    @gossip = Gossip.find(params[:gossip_id].to_i)
    @comment = Comment.new(content: params[:content], gossip: @gossip, user: current_user)
    if @comment.save
      flash[:success] = "Well done, your comment has been created successfully !"
      redirect_to gossip_path(params[:gossip_id].to_i)
    elsif
      flash.now[:danger] = "The comment could not be created"
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id].to_i)
    if @comment.user != current_user
      flash[:danger] = "You cannot edit this comment."
      redirect_to gossip_path(params[:gossip_id].to_i)
    end
  end

  def update
    @comment = Comment.find(params[:id].to_i)
    if @comment.user == current_user
      if @comment.update(content: params[:content])
        flash[:success] = "Well done, your comment has been updated successfully !"
        redirect_to gossip_path(params[:gossip_id].to_i)
      elsif
        flash.now[:error] = true
        render :edit
      end
    else
      flash[:danger] = "You cannot modify this comment."
      redirect_to gossip_path(params[:gossip_id].to_i)
    end
  end

  def destroy
    @comment = Comment.find(params[:id].to_i)
    if @comment.user == current_user
      if @comment.delete
        flash[:success] = "Well done, your comment has been deleted successfully !"
        redirect_to gossip_path(params[:gossip_id].to_i)
      elsif
        flash.now[:error] = true
        redirect_to gossip_path(params[:gossip_id].to_i)
      end
    else
      flash[:danger] = "You cannot delete this comment."
      redirect_to gossip_path(params[:gossip_id].to_i)
    end
  end

private

  def authenticate_user
    unless current_user
    flash[:danger] = "Please log in."
    redirect_to new_session_path
    end
  end

end

app/controllers/like_controller.rb
class LikeController < ApplicationController
before_action :authenticate_user, only: [:destroy, :create]

  def create
    @like = Like.create(user_id: current_user.id, gossip_id: params[:gossip_id])
    redirect_to request.referrer
  end
  
  def destroy
    @like = Like.find(params[:id])
    @like.delete
    redirect_to request.referrer
  end

private

  def authenticate_user
    unless current_user
    flash[:danger] = "Please log in."
    redirect_to new_session_path
    end
  end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
	def current_user
		User.find_by(id: session[:user_id])
	end

	def log_in(user)
		session[:user_id] = user.id
	end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/team_page_helper.rb
module TeamPageHelper
end

app/helpers/tgp_helper.rb
module TgpHelper
end

app/views/comments/edit.html.erb
<!-- ALERT MESSAGE IF INVALID GOSSIP -->

<% if flash[:error] %>
	<div class="alert alert-danger" role="alert">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  <p>The comment could not be edited due to the following reason(s) :</p>
	  <ul>
	    <% @comment.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	  </div>
<% end %>


<!-- EDIT COMMENT FORM -->
<br />
<div class = "center">
	<h1>Edit your comment !</h1>
	<br />

	<%= form_tag gossip_comment_path, method: "patch" do %>

		  <span><strong><%= label_tag 'Content'%></strong></span>
		  <%= text_area_tag 'content', @comment.content, class: "form-control", rows:"5" %>
		  <br /> 

	  	<%= submit_tag "Update comment", class: "btn btn-warning btn-lg btn-block" %>

	<% end %>
	<br/>
	<span class="btn btn-danger btn-lg btn-block" role="button"> <%= link_to "Delete the comment", gossip_comment_path(@comment.id), method: :delete, data: {confirm: "Are you sure?"}, style: 'color:#FFFFFF;', class: 'css_class' %>
	</span>
</div>

app/views/comments/index.html.erb
<!-- Comments Cards -->
<div class = "container list" >
	<h1> Here are all the <%= @all_gossip.comment.size %> comments : </h1>
	<br/>
	<div class = "row">
		<% @all_gossip.comment.each_with_index do |comment, i| %>
			<div class="card col-xs-12 col-sm-12 col-md-4 col-lg-4">
			  <div class="card-body">
			  	<h3><%= comment.content%></h3>
			    <p><%= comment.user %></p>
			    <% if current_user == @comment.user %>
					<span class="btn btn-warning" role="button"> <%= link_to "Edit the gossip", edit_gossip_comment_path(@comment.id), style: 'color:#000000;', class: 'css_class' %>
					</span>
				<% end %>
			  </div>
			</div>
		<% end %>
	</div>
</div>

app/views/comments/new.html.erb
<!-- ALERT MESSAGE IF INVALID COMMENT -->

<% if flash[:error] %>
	<div class="alert alert-danger" role="alert">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  <p>The comment could not be created</p>
	  </div>
<% end %>


<!-- CREATE CONTENT FORM -->
<br />
<div class = "center">
	<h1>Comment this gossip !</h1>
	<br />

	<%= form_tag gossip_comments_path, method: "post" do %>

		  <span><strong><%= label_tag 'Content'%></strong></span>
		  <%= text_area_tag 'content', nil , class: "form-control", placeholder: "Write your comment", rows:"5" %>
		  <br /> 

	  	<%= submit_tag "Submit comment", class: "btn btn-primary btn-lg btn-block" %>

	<% end %>
</div>