config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  resources :gossips do
  		resources :comments
  end
  resources :user
  resources :team, only:[:index]
  resources :contacts, only:[:index]
  resources :city, only:[:show]
  resources :session, only:[:new, :create, :destroy]
  resources :like, only:[:create, :destroy]
  # get 'welcome/', to: 'gossip#home'
  # get 'welcome/:user_name', to: 'gossip#homesecret', as: 'welcome_secret'
  # get 'gossip/:id', to:'gossip#index', as: 'gossip'
  # get 'create_gossip', to: 'gossip#create_gossip'
  # get 'contacts', to: 'gossip#contacts'
  # get 'team', to: 'gossip#team'
  # get 'user/:id', to:'gossip#user', as: 'user'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.or/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	#validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	belongs_to :commentable, polymorphic: true, optional: true
	has_many :likes
	has_many :comments, as: :commentable
	validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :join_gossip_tags
	has_many :tags, through: :join_gossip_tags
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	validates :title, 
		presence: true,
		length: {in: 3..50, message: "length must be between 3 and 50 characters long"}
	validates :content,
		presence: {message: "must exist"} 
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip, optional: true
	belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	has_many :recipient_lists
	validates :content, presence: {message: "must exist"} 
end

app/models/recipient_list.rb
class RecipientList < ApplicationRecord
	belongs_to :private_message
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_gossip_tags
	has_many :gossips, through: :join_gossip_tags
	validates :title, presence: {message: "Please indicate a title for your tag"} 
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
	has_many :comments
	validates :first_name, presence: {message: "must exist"} 
	validates :last_name, presence: {message: "must exist"} 
	validates :age, presence: {message: "must exist"} 
	validates :email, 
		presence: {message: "must be indicated"},
		uniqueness: {message: "already exists"},
		format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Enter a valid email format xxx@yyy.zzz" }
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def index
  end

  def show
    @city = City.find(params[:id].to_i)
    @all_users = @city.users
    puts "$"*10
    puts @city
    puts @all_users
    puts "$"*10
  end

  def new
  end
  
  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
before_action :authenticate_user, only: [:new, :edit, :update, :destroy, :create]

  # def index_secret
  #   @user_name = params[:user_name]
  #   @all_gossips = Gossip.all
  # end

  def index
    @all_gossips = Gossip.order(:id).all
    @gossip = Gossip.new
  end

  def show
    @gossip = Gossip.find(params[:id].to_i)
  end

  def new
  end
  
  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)
    if @gossip.save
      flash[:success] = "Well done, your gossip has been created successfully !"
      redirect_to gossips_path
    elsif
      flash.now[:error] = true
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id].to_i)
    if @gossip.user != current_user
      flash[:danger] = "You cannot edit this gossip."
      redirect_to gossips_path
    end
  end

  def update
    @gossip = Gossip.find(params[:id].to_i)
    if @gossip.user == current_user
      if @gossip.update(title: params[:title], content: params[:content])
        flash[:success] = "Well done, your gossip has been updated successfully !"
        redirect_to gossips_path
      elsif
        flash.now[:error] = true
        render :edit
      end
    else
      flash[:danger] = "You cannot modify this gossip."
      render :show
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id].to_i)
    if @gossip.user == current_user
      if @gossip.delete
        flash[:success] = "Your gossip has been deleted successfully !"
        redirect_to gossips_path
      elsif
        flash.now[:error] = true
        render :show
      end
    else
      flash.now[:danger] = "You cannot delete this gossip."
      render :show
    end
  end

private

  def authenticate_user
    unless current_user
    flash[:danger] = "Please log in."
    redirect_to new_session_path
    end
  end

end

app/controllers/like_controller.rb
class LikeController < ApplicationController
before_action :authenticate_user, only: [:destroy, :create]

  def create
    @like = Like.create(user_id: current_user.id, gossip_id: params[:gossip_id])
    redirect_to request.referrer
  end
  
  def destroy
    @like = Like.find(params[:id])
    @like.delete
    redirect_to request.referrer
  end

private

  def authenticate_user
    unless current_user
    flash[:danger] = "Please log in."
    redirect_to new_session_path
    end
  end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def index
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id].to_i)
    @cityid = @user.city.id
  end

  def new
  end
  
  def create
    @city = City.find_by(name: params[:city])
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], age: params[:age], email: params[:email], description: params[:description], city: @city ,password: params[:password], password_confirmation: params[:password_confirmation])
    if @user.save
      flash[:success] = "Well done, your account has been created successfully !"
      log_in(@user)
      redirect_to gossips_path
    elsif
      flash.now[:error] = true
      render :new
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    @city = City.find_by(name: params[:city])
    if @user.update(first_name: params[:first_name], last_name: params[:last_name], age: params[:age], email: params[:email], description: params[:description], city: @city)
      flash[:success] = "Well done, your profile has been updated successfully !"
      redirect_to gossips_path
    elsif
      flash.now[:error] = true
      render :edit
    end
  end

  def destroy

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
	def current_user
		User.find_by(id: session[:user_id])
	end

	def log_in(user)
		session[:user_id] = user.id
	end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/team_page_helper.rb
module TeamPageHelper
end

app/helpers/tgp_helper.rb
module TgpHelper
end

app/views/gossip/contacts.html.erb
<h1>Sorry je donne pas mon 06 facilement</h1>

app/views/gossip/team.html.erb
<h1>Partner in crime !</h1>

app/views/gossips/edit.html.erb
<!-- ALERT MESSAGE IF INVALID GOSSIP -->

<% if flash[:error] %>
	<div class="alert alert-danger" role="alert">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  <p>The gossip could not be created due to the following reason(s) :</p>
	  <ul>
	    <% @gossip.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	  </div>
<% end %>


<!-- EDIT GOSSIP FORM -->
<br />
<div class = "center">
	<h1>Edit your gossip !</h1>
	<br />

	<%= form_tag gossip_path, method: "patch" do %>

		  <span><strong><%= label_tag 'Title'%></strong></span>
		  <%= text_field_tag 'title', @gossip.title, class: "form-control" %>
		  <br /> 

		  <span><strong><%= label_tag 'Content'%></strong></span>
		  <%= text_area_tag 'content', @gossip.content, class: "form-control", rows:"5" %>
		  <br /> 

	  	<%= submit_tag "Update Gossip", class: "btn btn-warning btn-lg btn-block" %>

	<% end %>
	<br/>
	<span class="btn btn-danger btn-lg btn-block" role="button"> <%= link_to "Delete the gossip", gossip_path(@gossip.id), method: :delete, data: {confirm: "Are you sure?"}, style: 'color:#FFFFFF;', class: 'css_class' %>
	</span>
</div>

app/views/gossips/index.html.erb
<!-- Welcome Jumbotron -->
<div class = "container jumb">
	<div class="jumbotron">
	  <h2 class="display-1" style='color:#FFFFFF;'>Welcome 
	  	<% if current_user %>
	  	<%= current_user.first_name %>!
		<% end %>
	  </h2>
	  <h3 style='color:#FFFFFF;'>This is my funny Gossip application :)</h3>
	  <hr class="my-4">
	  <p class="lead" style='color:#FFFFFF;'>Click on the button below to create a new Gossip.</p>
	  <p class="lead">
	    <span class="btn btn-primary btn-lg" role="button"> <%= link_to "New Gossip", new_gossip_path, style: 'color:#FFFFFF;', class: 'css_class'  %>
	    </span>
	  </p>
	</div>
</div>

<!-- Gossip Cards -->
<div class = "container list" >
	<h1> Here are all the <%= @all_gossips.size %> gossips : </h1>
	<br/>
	<div class = "row">
		<% @all_gossips.each_with_index do |gossip, i| %>
			<div class="card col-xs-12 col-sm-12 col-md-4 col-lg-4">
			  <div class="card-body">
			  	<h3><%= gossip.title %></h3>
			    <p><%= gossip.user.first_name %> <%= gossip.user.last_name %></p>
			    <p><%= gossip.comments.count %> comments</p>
				<span class="btn btn-warning" role="button"> <%= link_to "View Gossip", gossip_path(gossip.id), style: 'color:#000000;', class: 'css_class' %>
			    </span>
			    <% if current_user %>
				    <% if current_user.id.in?(gossip.likes.pluck(:user_id)) %>
					    <button type="button" class="btn btn-primary btn-md">
						  <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> 
						  <%= link_to gossip.likes.count, {:controller => "like", :action => "destroy", :id => Like.find_by(user_id: current_user.id, gossip_id: gossip.id).id}, method: :delete, style: 'color:#FFFFFF;'%>
						  <!-- like_path(Like.find_by(user_id: current_user.id, gossip_id: gossip.id))-->
						</button>
					<% else %>
						<button type="button" class="btn btn-default btn-md">
						  <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
						  <%= link_to gossip.likes.count,{:controller => "like", :action => "create", :gossip_id => gossip.id}, method: :post, style: 'color:#000000;'%>
						</button>
					<% end %>
				<% end %>
			  </div>
			</div>
		<% end %>
	</div>
</div>

app/views/gossips/index_secret.html.erb
<!-- Welcome Jumbotron -->
<div class = "container jumb">
	<div class="jumbotron">
	  <h2 class="display-1">Welcome <%=@user_name%> !</h2>
	  <p class="lead">This is my funny Gossip application !</p>
	  <hr class="my-4">
	  <p>Click on the button below to create a new Gossip.</p>
	  <p class="lead">
	    <span class="btn btn-primary btn-lg" role="button"> <%= link_to "New Gossip", new_gossip_path, style: 'color:#FFFFFF;', class: 'css_class'  %>
	    </span>
	  </p>
	</div>
</div>
<!-- Gossip Cards <--></-->
<div class = "container">
	<h1> Here are all the gossips : </h1>
	<br/>
	<div class = "row">
		<% @all_gossips.each_with_index do |gossip, i| %>
			<div class="card col-xs-12 col-sm-12 col-md-4 col-lg-4">
			  <div class="card-body">
			  	<h3><%= gossip.title %></h3>
			    <p><%= gossip.user.first_name %> <%= gossip.user.last_name %></p>
				<span class="btn btn-warning" role="button"> <%= link_to "View Gossip", gossip_path(i+1), style: 'color:#000000;', class: 'css_class' %>
			    </span>
			  </div>
			</div>
		<% end %>
	</div>
</div>

app/views/gossips/new.html.erb
<!-- ALERT MESSAGE IF INVALID GOSSIP -->

<% if flash[:error] %>
	<div class="alert alert-danger" role="alert">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  <p>The gossip could not be created due to the following reason(s) :</p>
	  <ul>
	    <% @gossip.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	  </div>
<% end %>


<!-- CREATE GOSSIP FORM -->
<br />
<div class = "center">
	<h1>Create your gossip !</h1>
	<br />

	<%= form_tag gossips_path, method: "post" do %>

		  <span><strong><%= label_tag 'Title'%></strong></span>
		  <%= text_field_tag 'title', 'Your gossip title', class: "form-control" %>
		  <br /> 

		  <span><strong><%= label_tag 'Content'%></strong></span>
		  <%= text_area_tag 'content', 'Write your gossip', class: "form-control", rows:"5" %>
		  <br /> 

	  	<%= submit_tag "Create Gossip", class: "btn btn-primary btn-lg btn-block" %>

	<% end %>
</div>

app/views/gossips/show.html.erb
<!-- ALERT MESSAGE IF UNSUCCESSFUL CREATION -->
<% if flash[:error] %>
	<div class="alert alert-danger" role="alert">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  <p>The gossip could not be created due to the following reason(s) :</p>
	  <ul>
	    <% @gossip.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	  </div>
<% end %>

<!-- GOSSIP CONTAINER -->
<div class = "container gossip">
	<div class = "row">
		<article class = "card col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<h1> <%= @gossip.title %></h1>
			<br/>
			<h4> <%= @gossip.content %> </h4>
			<br/>
			<p><em><strong> Author : </strong><%= @gossip.user.first_name %> <%= @gossip.user.last_name %>, from <%= @gossip.user.city.name %></em></p>
		</article>
	</div>
	<br/>
	<span class="btn btn-secondary" role="button"> <%= link_to "Go to author's profile page", user_path(@gossip.user.id), style: 'color:#FFFFFF;', class: 'css_class' %>
	</span>
	<span class="btn btn-info" role="button"> <%= link_to "Add a comment", new_gossip_comment_path(@gossip.id), style: 'color:#FFFFFF;', class: 'css_class' %>
	</span>
	<% if current_user == @gossip.user %>
		<span class="btn btn-warning" role="button"> <%= link_to "Edit the gossip", edit_gossip_path(@gossip.id), style: 'color:#000000;', class: 'css_class' %>
		</span>
	<% end %>
	<% if current_user %>
	    <% if current_user.id.in?(@gossip.likes.pluck(:user_id)) %>
		    <button type="button" class="btn btn-primary btn-md">
			  <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> 
			  <%= link_to @gossip.likes.count, {:controller => "like", :action => "destroy", :id => Like.find_by(user_id: current_user.id, gossip_id: @gossip.id).id}, method: :delete, style: 'color:#FFFFFF;'%>
			</button>
		<% else %>
			<button type="button" class="btn btn-default btn-md">
			  <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
			  <%= link_to @gossip.likes.count,{:controller => "like", :action => "create", :gossip_id => @gossip.id}, method: :post, style: 'color:#000000;'%>
			</button>
		<% end %>
	<% end %>
</div>

<!-- COMMENTS LIST -->
<div class = "container list" >
	<h1> <%= @gossip.comments.size %> comments : </h1>
	<br/>
	<div class = "row">
		<% @gossip.comments.each_with_index do |comment, i| %>
			<div class="card col-xs-12 col-sm-12 col-md-4 col-lg-4">
			  <div class="card-body">
			  	<h3><%= comment.content %></h3>
			    <p><%= comment.user.first_name %> <%= comment.user.last_name %></p>
			    <% if current_user == comment.user %>
					<span class="btn btn-warning" role="button"> <%= link_to "Edit the comment", edit_gossip_comment_path(@gossip.id, comment.id), style: 'color:#000000;', class: 'css_class' %>
					</span>
					<span class="btn btn-danger" role="button"> <%= link_to "Delete the comment", gossip_comment_path(@gossip.id, comment.id), method: :delete,style: 'color:#000000;', class: 'css_class' %>
					</span>
				<% end %>
			  </div>
			</div>
		<% end %>
	</div>
</div>


	