config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  resources :gossips do
  		resources :comments
  end
  resources :user
  resources :team, only:[:index]
  resources :contacts, only:[:index]
  resources :city, only:[:show]
  resources :session, only:[:new, :create, :destroy]
  resources :like, only:[:create, :destroy]
  # get 'welcome/', to: 'gossip#home'
  # get 'welcome/:user_name', to: 'gossip#homesecret', as: 'welcome_secret'
  # get 'gossip/:id', to:'gossip#index', as: 'gossip'
  # get 'create_gossip', to: 'gossip#create_gossip'
  # get 'contacts', to: 'gossip#contacts'
  # get 'team', to: 'gossip#team'
  # get 'user/:id', to:'gossip#user', as: 'user'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.or/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	#validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	belongs_to :commentable, polymorphic: true, optional: true
	has_many :likes
	has_many :comments, as: :commentable
	validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :join_gossip_tags
	has_many :tags, through: :join_gossip_tags
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	validates :title, 
		presence: true,
		length: {in: 3..50, message: "length must be between 3 and 50 characters long"}
	validates :content,
		presence: {message: "must exist"} 
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip, optional: true
	belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	has_many :recipient_lists
	validates :content, presence: {message: "must exist"} 
end

app/models/recipient_list.rb
class RecipientList < ApplicationRecord
	belongs_to :private_message
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_gossip_tags
	has_many :gossips, through: :join_gossip_tags
	validates :title, presence: {message: "Please indicate a title for your tag"} 
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
	has_many :comments
	validates :first_name, presence: {message: "must exist"} 
	validates :last_name, presence: {message: "must exist"} 
	validates :age, presence: {message: "must exist"} 
	validates :email, 
		presence: {message: "must be indicated"},
		uniqueness: {message: "already exists"},
		format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Enter a valid email format xxx@yyy.zzz" }
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def index
  end

  def show
    @city = City.find(params[:id].to_i)
    @all_users = @city.users
    puts "$"*10
    puts @city
    puts @all_users
    puts "$"*10
  end

  def new
  end
  
  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/like_controller.rb
class LikeController < ApplicationController
before_action :authenticate_user, only: [:destroy, :create]

  def create
    @like = Like.create(user_id: current_user.id, gossip_id: params[:gossip_id])
    redirect_to request.referrer
  end
  
  def destroy
    @like = Like.find(params[:id])
    @like.delete
    redirect_to request.referrer
  end

private

  def authenticate_user
    unless current_user
    flash[:danger] = "Please log in."
    redirect_to new_session_path
    end
  end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def index
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id].to_i)
    @cityid = @user.city.id
  end

  def new
  end
  
  def create
    @city = City.find_by(name: params[:city])
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], age: params[:age], email: params[:email], description: params[:description], city: @city ,password: params[:password], password_confirmation: params[:password_confirmation])
    if @user.save
      flash[:success] = "Well done, your account has been created successfully !"
      log_in(@user)
      redirect_to gossips_path
    elsif
      flash.now[:error] = true
      render :new
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    @city = City.find_by(name: params[:city])
    if @user.update(first_name: params[:first_name], last_name: params[:last_name], age: params[:age], email: params[:email], description: params[:description], city: @city)
      flash[:success] = "Well done, your profile has been updated successfully !"
      redirect_to gossips_path
    elsif
      flash.now[:error] = true
      render :edit
    end
  end

  def destroy

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
	def current_user
		User.find_by(id: session[:user_id])
	end

	def log_in(user)
		session[:user_id] = user.id
	end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/team_page_helper.rb
module TeamPageHelper
end

app/helpers/tgp_helper.rb
module TgpHelper
end

app/views/city/show.html.erb
<br/>
<div class = "container list" >
	<h1> Here are all the gossips from <%= @city.name %>: </h1>
	<br/>
	<div class = "row">
		<% @all_users.each do |user| %>
			<% user.gossips.each_with_index do |gossip,i| %>
				<div class="card col-xs-12 col-sm-12 col-md-4 col-lg-4">
				  <div class="card-body">
				  	<h3><%= gossip.title %></h3>
				    <p><%= gossip.user.first_name %> <%= gossip.user.last_name %></p>
					<span class="btn btn-warning" role="button"> <%= link_to "View Gossip", gossip_path(gossip.id), style: 'color:#000000;', class: 'css_class' %>
				    </span>
	 				<% if current_user %>
					    <% if current_user.id.in?(gossip.likes.pluck(:user_id)) %>
						    <button type="button" class="btn btn-primary btn-md">
							  <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> 
							  <%= link_to gossip.likes.count, {:controller => "like", :action => "destroy", :id => Like.find_by(user_id: current_user.id, gossip_id: gossip.id).id}, method: :delete, style: 'color:#FFFFFF;'%>
							  <!-- like_path(Like.find_by(user_id: current_user.id, gossip_id: gossip.id))-->
							</button>
						<% else %>
							<button type="button" class="btn btn-default btn-md">
							  <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
							  <%= link_to gossip.likes.count,{:controller => "like", :action => "create", :gossip_id => gossip.id}, method: :post, style: 'color:#000000;'%>
							</button>
						<% end %>
					<% end %>
				  </div>
				</div>
			<% end %>
		<% end %>
	</div>
</div>

app/views/team/index.html.erb
<!-- Section: Team v.1 -->
<section class="team-section text-center my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold my-5">Our amazing team</h2>
  <!-- Section description -->
  <p class="grey-text w-responsive mx-auto mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    Fugit, error amet numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum quisquam
    eum porro a pariatur veniam.</p>

  <!-- Grid row -->
  <div class="row">

    <!-- Grid column -->
    <div class="col-lg-3 col-md-6 mb-lg-0 mb-5">
      <div class="avatar mx-auto">
        <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(20).jpg" class="rounded-circle z-depth-1"
          alt="Sample avatar">
      </div>
      <h5 class="font-weight-bold mt-4 mb-3">Anna Williams</h5>
      <p class="text-uppercase blue-text"><strong>Graphic designer</strong></p>
      <p class="grey-text">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
        adipisci sed quia non numquam modi tempora eius.</p>
      <ul class="list-unstyled mb-0">
        <!-- Facebook -->
        <a class="p-2 fa-lg fb-ic">
          <i class="fab fa-facebook-f blue-text"> </i>
        </a>
        <!-- Twitter -->
        <a class="p-2 fa-lg tw-ic">
          <i class="fab fa-twitter blue-text"> </i>
        </a>
        <!-- Instagram -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-instagram blue-text"> </i>
        </a>
      </ul>
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-3 col-md-6 mb-lg-0 mb-5">
      <div class="avatar mx-auto">
        <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(3).jpg" class="rounded-circle z-depth-1"
          alt="Sample avatar">
      </div>
      <h5 class="font-weight-bold mt-4 mb-3">John Doe</h5>
      <p class="text-uppercase blue-text"><strong>Web developer</strong></p>
      <p class="grey-text">Sed ut perspiciatis unde omnis iste natus error sit voluptatem ipsa accusantium
        doloremque rem laudantium totam aperiam.</p>
      <ul class="list-unstyled mb-0">
        <!-- Facebook -->
        <a class="p-2 fa-lg fb-ic">
          <i class="fab fa-facebook-f blue-text"> </i>
        </a>
        <!-- Instagram -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-instagram blue-text"> </i>
        </a>
      </ul>
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-3 col-md-6 mb-md-0 mb-5">
      <div class="avatar mx-auto">
        <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(30).jpg" class="rounded-circle z-depth-1"
          alt="Sample avatar">
      </div>
      <h5 class="font-weight-bold mt-4 mb-3">Maria Smith</h5>
      <p class="text-uppercase blue-text"><strong>Photographer</strong></p>
      <p class="grey-text">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
        mollit anim est fugiat nulla id eu laborum.</p>
      <ul class="list-unstyled mb-0">
        <!-- Facebook -->
        <a class="p-2 fa-lg fb-ic">
          <i class="fab fa-facebook-f blue-text"> </i>
        </a>
        <!-- Instagram -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-instagram blue-text"> </i>
        </a>
        <!-- Dribbble -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-dribbble blue-text"> </i>
        </a>
      </ul>
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-3 col-md-6">
      <div class="avatar mx-auto">
        <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(32).jpg" class="rounded-circle z-depth-1"
          alt="Sample avatar">
      </div>
      <h5 class="font-weight-bold mt-4 mb-3">Tom Adams</h5>
      <p class="text-uppercase blue-text"><strong>Backend developer</strong></p>
      <p class="grey-text">Perspiciatis repellendus ad odit consequuntur, eveniet earum nisi qui consectetur
        totam officia voluptates perferendis voluptatibus aut.</p>
      <ul class="list-unstyled mb-0">
        <!-- Facebook -->
        <a class="p-2 fa-lg fb-ic">
          <i class="fab fa-facebook-f blue-text"> </i>
        </a>
        <!-- Github -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-github blue-text"> </i>
        </a>
      </ul>
    </div>
    <!-- Grid column -->

  </div>
  <!-- Grid row -->

</section>
<!-- Section: Team v.1 -->

app/views/user/edit.html.erb
<!-- ALERT MESSAGE IF INVALID ACCOUNT -->

<% if flash[:error] %>
	<div class="alert alert-danger" role="alert">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  <p>The account could not be created due to the following reason(s) :</p>
	  <ul>
	    <% @user.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	  </div>
<% end %>


<!-- EDIT PROFILE FORM -->
<br />
<div class = "center">
	<h1>Change your profile !</h1>
	<br />

	<%= form_tag user_path, method: "patch" do %>

		  <span><strong><%= label_tag 'First Name'%></strong></span>
		  <%= text_field_tag 'first_name', @user.first_name, class: "form-control"%>
		  <br /> 

		  <span><strong><%= label_tag 'Last Name'%></strong></span>
		  <%= text_field_tag 'last_name', @user.last_name, class: "form-control" %>
		  <br /> 

		  <span><strong><%= label_tag 'Age'%></strong></span>
		  <%= text_field_tag 'age', @user.age, class: "form-control"%>
		  <br />

		  <span><strong><%= label_tag 'City'%></strong></span>
		  <%= select_tag 'city', options_for_select(City.pluck(:name)), class: "form-control"%>
		  <br />

		  <span><strong><%= label_tag 'Description'%></strong></span>
		  <%= text_area_tag 'description', @user.description, class: "form-control"%>
		  <br />

		  <span><strong><%= label_tag 'Email address'%></strong></span>
		  <%= text_field_tag 'email', @user.email, class: "form-control"%>
		  <br />

	  	<%= submit_tag "Edit profile", class: "btn btn-primary btn-lg btn-block" %>
	<br />
	<% end %>
	<br />
	<br />
</div>

app/views/user/new.html.erb
<!-- ALERT MESSAGE IF INVALID ACCOUNT -->

<% if flash[:error] %>
	<div class="alert alert-danger" role="alert">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  <p>The account could not be created due to the following reason(s) :</p>
	  <ul>
	    <% @user.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	  </div>
<% end %>


<!-- CREATE ACCOUNT FORM -->
<br />
<div class = "center">
	<h1>Create your account !</h1>
	<br />

	<%= form_tag user_index_path, method: "post" do %>

		  <span><strong><%= label_tag 'First Name'%></strong></span>
		  <%= text_field_tag 'first_name', nil, class: "form-control", placeholder: 'Your first name' %>
		  <br /> 

		  <span><strong><%= label_tag 'Last Name'%></strong></span>
		  <%= text_field_tag 'last_name', nil, class: "form-control", placeholder: 'Your last name'  %>
		  <br /> 

		  <span><strong><%= label_tag 'Age'%></strong></span>
		  <%= text_field_tag 'age', nil, class: "form-control", placeholder: '99'  %>
		  <br />

		  <span><strong><%= label_tag 'City'%></strong></span>
		  <%= select_tag 'city', options_for_select(City.pluck(:name)), class: "form-control"%>
		  <br />

		  <span><strong><%= label_tag 'Description'%></strong></span>
		  <%= text_area_tag 'description', nil, class: "form-control", placeholder: 'Your description'  %>
		  <br />

		  <span><strong><%= label_tag 'Email address'%></strong></span>
		  <%= text_field_tag 'email', nil, class: "form-control", placeholder: 'azerty#qwerty.com'  %>
		  <br />

		  <span><strong><%= label_tag 'Password'%></strong></span>
		  <%= text_field_tag 'password', nil, class: "form-control", type: 'password', placeholder: 'Choose a password'%>
		  <br />

		  <span><strong><%= label_tag 'Confirm your password'%></strong></span>
		  <%= text_field_tag 'password_confirmation', nil, class: "form-control", type: 'password', placeholder: 'Confirm your password'  %>
		  <br />

	  	<%= submit_tag "Create account", class: "btn btn-primary btn-lg btn-block" %>
	<br />
	<% end %>
	<br />
	<br />
</div>

app/views/user/show.html.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

 <div class="container prof">
   <h1> Profile Page </h1>
   <br/>
    <div class="row">
        <div class="col-sm-4 col-md-4">
            <img src="https://img.20mn.fr/meUBriI8Q8uqlURJQoQghA/1200x768_acteur-joaquin-phoenix-sous-traits-joker.jpg"
            alt="" class="img-rounded img-responsive" />
        </div>
        <div class="col-sm-6 col-md-6">
            <blockquote>
                <p style="font-size:24px"><%= @user.first_name %> <%= @user.last_name %></p> <cite title="Source Title"><%= link_to @user.city.name, city_path(@cityid) %> <i class="glyphicon glyphicon-map-marker"></i></cite>
            </blockquote>
            <p> <i class="glyphicon glyphicon-envelope"></i> <%= @user.email %> 
                <br/> 
                <br/> <i class="glyphicon glyphicon-gift"></i> January 30, <%= 2019 - @user.age %> </p>
                <p> <%= @user.description %> </p>
        </div>
      
     