config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  resources :gossips do
  		resources :comments
  end
  resources :user
  resources :team, only:[:index]
  resources :contacts, only:[:index]
  resources :city, only:[:show]
  resources :session, only:[:new, :create, :destroy]
  resources :like, only:[:create, :destroy]
  # get 'welcome/', to: 'gossip#home'
  # get 'welcome/:user_name', to: 'gossip#homesecret', as: 'welcome_secret'
  # get 'gossip/:id', to:'gossip#index', as: 'gossip'
  # get 'create_gossip', to: 'gossip#create_gossip'
  # get 'contacts', to: 'gossip#contacts'
  # get 'team', to: 'gossip#team'
  # get 'user/:id', to:'gossip#user', as: 'user'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.or/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	#validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	belongs_to :commentable, polymorphic: true, optional: true
	has_many :likes
	has_many :comments, as: :commentable
	validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :join_gossip_tags
	has_many :tags, through: :join_gossip_tags
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	validates :title, 
		presence: true,
		length: {in: 3..50, message: "length must be between 3 and 50 characters long"}
	validates :content,
		presence: {message: "must exist"} 
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip, optional: true
	belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	has_many :recipient_lists
	validates :content, presence: {message: "must exist"} 
end

app/models/recipient_list.rb
class RecipientList < ApplicationRecord
	belongs_to :private_message
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_gossip_tags
	has_many :gossips, through: :join_gossip_tags
	validates :title, presence: {message: "Please indicate a title for your tag"} 
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
	has_many :comments
	validates :first_name, presence: {message: "must exist"} 
	validates :last_name, presence: {message: "must exist"} 
	validates :age, presence: {message: "must exist"} 
	validates :email, 
		presence: {message: "must be indicated"},
		uniqueness: {message: "already exists"},
		format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Enter a valid email format xxx@yyy.zzz" }
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def index
  end

  def show
    @city = City.find(params[:id].to_i)
    @all_users = @city.users
    puts "$"*10
    puts @city
    puts @all_users
    puts "$"*10
  end

  def new
  end
  
  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/like_controller.rb
class LikeController < ApplicationController
before_action :authenticate_user, only: [:destroy, :create]

  def create
    @like = Like.create(user_id: current_user.id, gossip_id: params[:gossip_id])
    redirect_to request.referrer
  end
  
  def destroy
    @like = Like.find(params[:id])
    @like.delete
    redirect_to request.referrer
  end

private

  def authenticate_user
    unless current_user
    flash[:danger] = "Please log in."
    redirect_to new_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
	def current_user
		User.find_by(id: session[:user_id])
	end

	def log_in(user)
		session[:user_id] = user.id
	end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/team_page_helper.rb
module TeamPageHelper
end

app/helpers/tgp_helper.rb
module TgpHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="app/assets/stylesheets/application.css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  </head>

  <body>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">


      <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "The Gossip Project", gossips_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Team", team_index_path, class: "nav-link", style: 'color:#FFFFFF' %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contacts_path, class: "nav-link", style: 'color:#FFFFFF' %>
          </li>
          <%unless current_user %>
          <li class="nav-item">
            <%= link_to "Log in", new_session_path(session.id), class: "nav-link", style: 'color:#FFFFFF' %>
          </li>
          <li class="nav-item">
              <%= link_to "Sign In", new_user_path, class: "nav-link", style: 'color:#FFFFFF' %>
          </li>
          <% end %>
        </ul>
      </div>
      <%if current_user %>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Nav Options
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to "Edit profile", edit_user_path(session.id), class: "dropdown-item" %>
              <%= link_to "Log out", session_path(session.id), method: :delete, class: "dropdown-item" %>
            </div>
          </div>  
      <% end %>
    </nav>
  

      <!-- Alert status -->
    <% if flash[:success] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:success] %>
      </div>
    <%elsif flash[:danger] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:danger] %>
      </div>
    <% end %>


    <%= yield %>

  </body>
</html>